apiVersion: v1
kind: Service
metadata:
  name: gap-service
  labels:
    app: gap-app
spec:
  type: NodePort
  selector:
    app: gap
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
